title: Default Page
icon: page

tabs:
  content:
    label: Content
    icon: page
    columns:
      main:
        width: 2/3
        label: Content
        icon: page
        fields:
          text:
            type: textarea
            label: Text
            size: large
      sidebar:
        width: 1/3
        sections:
          files: sections/files

  meta: tabs/meta/page

